name: CI
on:
  - repository_dispatch:
    types: [on-demand-test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Pull submodule
        run: |
          git pull --recurse-submodules
          git submodule update --init vendor/vendor-1
          git submodule update --init vendor/vendor-2
          git submodule update --remote vendor/vendor-1
          git submodule update --remote vendor/vendor-2
      - name: Push changes
        run: |
          git config --global user.name 'github-action'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git add .
          git commit -m "Automated submodule update"
          git push
